services:
  resolver:
    image: ghcr.io/clementgre/archypix-resolver:${TAG}
    container_name: archypix-resolver
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.http.routers.resolver.rule: Host(`archypix.com`) && PathPrefix(`/archypix-resolver`)
      traefik.http.routers.resolver.priority: 100
      traefik.http.services.resolver.loadbalancer.server.port: 80
    environment:
      RUST_LOG: ${RUST_LOG}
      CORS_ORIGINS: "https://archypix.com"
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: archypix_resolver
      GLOBAL_DOMAIN: archypix.com
      RESOLVER_JWT_SECRET: ${RESOLVER_JWT_SECRET}
    networks:
      - archypix
      - traefik
      - postgres

  backend1:
    image: ghcr.io/clementgre/archypix-back:${TAG}
    container_name: archypix-back1
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.http.routers.archypix-backend1.rule: Host(`back1.archypix.com`)
      traefik.http.services.archypix-backend1.loadbalancer.server.port: 80
    environment:
      RUST_LOG: ${RUST_LOG}
      TRACE_PROPAGATION_PEERS: archypix.com
      OTEL_EXPORTER_OTLP_ENDPOINT: ${OTEL_EXPORTER_OTLP_ENDPOINT}
      BACK_DOMAIN: back1.archypix.com
      BACK_INTERNAL_URL: http://backend1
      GLOBAL_DOMAIN: archypix.com
      CORS_ORIGINS: "https://archypix.com"
      USE_RESOLVER: "true"
      RESOLVER_INTERNAL_URL: http://resolver
      RESOLVER_JWT_SECRET: ${RESOLVER_JWT_SECRET}
      WORKER_JWT_SECRET: ${WORKER_JWT_SECRET}
      JWT_SECRET: ${JWT_SECRET_1}
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: archypix_back1
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_DB: "1"
      S3_BUCKET_STAGING: b1-archypix-staging
      S3_BUCKET_PICTURES: b1-archypix-pictures
      S3_BUCKET_VERSIONS: b1-archypix-versions
      S3_BUCKET_SMALL: b1-archypix-small
      S3_BUCKET_MEDIUM: b1-archypix-medium
      S3_BUCKET_LARGE: b1-archypix-large
      S3_ENDPOINT: ${S3_ENDPOINT}
      S3_PUBLIC_ENDPOINT: ${S3_PUBLIC_ENDPOINT}
      S3_WORKERS_ENDPOINT: ${S3_WORKERS_ENDPOINT}
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_SECRET_KEY: ${S3_SECRET_KEY}
    depends_on:
      - resolver
      - minio
    networks:
      - archypix
      - traefik
      - postgres
      - redis

  backend2:
    image: ghcr.io/clementgre/archypix-back:${TAG}
    container_name: archypix-back2
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.http.routers.archypix-backend2.rule: Host(`back2.archypix.com`)
      traefik.http.services.archypix-backend2.loadbalancer.server.port: 80
    environment:
      RUST_LOG: ${RUST_LOG}
      TRACE_PROPAGATION_PEERS: archypix.com
      OTEL_EXPORTER_OTLP_ENDPOINT: ${OTEL_EXPORTER_OTLP_ENDPOINT}
      BACK_DOMAIN: back2.archypix.com
      BACK_INTERNAL_URL: http://backend2
      GLOBAL_DOMAIN: archypix.com
      CORS_ORIGINS: "https://archypix.com"
      USE_RESOLVER: "true"
      RESOLVER_INTERNAL_URL: http://resolver
      RESOLVER_JWT_SECRET: ${RESOLVER_JWT_SECRET}
      WORKER_JWT_SECRET: ${WORKER_JWT_SECRET}
      JWT_SECRET: ${JWT_SECRET_2}
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: archypix_back2
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_DB: "2"
      S3_BUCKET_STAGING: b2-archypix-staging
      S3_BUCKET_PICTURES: b2-archypix-pictures
      S3_BUCKET_VERSIONS: b2-archypix-versions
      S3_BUCKET_SMALL: b2-archypix-small
      S3_BUCKET_MEDIUM: b2-archypix-medium
      S3_BUCKET_LARGE: b2-archypix-large
      S3_ENDPOINT: ${S3_ENDPOINT}
      S3_PUBLIC_ENDPOINT: ${S3_PUBLIC_ENDPOINT}
      S3_WORKERS_ENDPOINT: ${S3_WORKERS_ENDPOINT}
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_SECRET_KEY: ${S3_SECRET_KEY}
    depends_on:
      - resolver
      - minio
    networks:
      - archypix
      - traefik
      - postgres
      - redis

  worker:
    image: ghcr.io/clementgre/archypix-worker:${TAG}
    container_name: archypix-worker
    restart: unless-stopped
    environment:
      RUST_LOG: ${RUST_LOG}
      OTEL_EXPORTER_OTLP_ENDPOINT: ${OTEL_EXPORTER_OTLP_ENDPOINT}
      WORKER_ID: worker
      BACK_URL: http://backend1,http://backend2
      BACK_DOMAIN: back1.archypix.com,back2.archypix.com
      GLOBAL_DOMAIN: archypix.com
      WORKER_JWT_SECRET: ${WORKER_JWT_SECRET}
    depends_on:
      - backend1
      - backend2
    networks:
      - archypix

  front:
    image: ghcr.io/clementgre/archypix-front:${TAG}
    container_name: archypix-front
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.http.routers.archypix-front.rule: Host(`archypix.com`)
      traefik.http.services.archypix-front.loadbalancer.server.port: 80
      traefik.http.routers.archypix-front.middlewares: authelia-archypix@docker
    environment:
      VITE_GLOBAL_DOMAIN: archypix.com
      VITE_USE_HTTPS: true
    networks:
      - archypix
      - traefik

  minio:
    image: minio/minio:latest
    container_name: archypix-minio
    restart: unless-stopped
    command: server /data --address :9000 --console-address :9001
    labels:
      traefik.enable: true
      traefik.http.routers.archypix-s1.rule: Host(`s3.archypix.com`)
      traefik.http.services.archypix-s3.loadbalancer.server.port: 9000
    ports:
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${S3_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${S3_SECRET_KEY}
    volumes:
      - /mnt/large/archypix-minio:/data
    networks:
      - archypix
      - traefik
    healthcheck:
      test: [ "CMD", "mc", "ready", "local" ]
      interval: 10s
      timeout: 2s
      retries: 2

networks:
  archypix:
    name: archypix
  postgres:
    external: true
  redis:
    external: true
  traefik:
    external: true

